<?php

use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
            $data = [
                [
                    'name' => 'Meramu',
                    'slug' => '1',
                    'description' => 'Meramu',
                    'price' => '0',
                    'stock' => '0',
                    'user_id' => '1',
                    'kategori_id' => '1',
                    'sku' => '1',
                    'weight' => '1',
                    'asuransi' => '1',
                    'long' => '1',
                    'width' => '1',
                    'height' => '1',
                    'status' => '1',
                    'views' => '1',
                    'kodisi' => '1',
                    'kelipatan' => '1',
                    'end_date' => '1',
                ],
                [
                    'name' => 'Love Language',
                    'slug' => '1',
                    'description' => 'Love Language',
                    'price' => '0',
                    'stock' => '0',
                    'user_id' => '1',
                    'kategori_id' => '1',
                    'sku' => '1',
                    'weight' => '1',
                    'asuransi' => '1',
                    'long' => '1',
                    'width' => '1',
                    'height' => '1',
                    'status' => '1',
                    'views' => '1',
                    'kodisi' => '1',
                    'kelipatan' => '1',
                    'end_date' => '1',
                ],
                [
                    'name' => 'Friend 4ever',
                    'slug' => '1',
                    'description' => 'Friend 4ever',
                    'price' => '0',
                    'stock' => '0',
                    'user_id' => '1',
                    'kategori_id' => '1',
                    'sku' => '1',
                    'weight' => '1',
                    'asuransi' => '1',
                    'long' => '1',
                    'width' => '1',
                    'height' => '1',
                    'status' => '1',
                    'views' => '1',
                    'kodisi' => '1',
                    'kelipatan' => '1',
                    'end_date' => '1',
                ],
                [
                    'name' => 'Team',
                    'slug' => '1',
                    'description' => 'team',
                    'price' => '0',
                    'stock' => '0',
                    'user_id' => '1',
                    'kategori_id' => '1',
                    'sku' => '1',
                    'weight' => '1',
                    'asuransi' => '1',
                    'long' => '1',
                    'width' => '1',
                    'height' => '1',
                    'status' => '1',
                    'views' => '1',
                    'kodisi' => '1',
                    'kelipatan' => '1',
                    'end_date' => '1',
                ],
                [
                    'name' => 'Boyband',
                    'slug' => '1',
                    'description' => 'boyband',
                    'price' => '0',
                    'stock' => '0',
                    'user_id' => '1',
                    'kategori_id' => '1',
                    'sku' => '1',
                    'weight' => '1',
                    'asuransi' => '1',
                    'long' => '1',
                    'width' => '1',
                    'height' => '1',
                    'status' => '1',
                    'views' => '1',
                    'kodisi' => '1',
                    'kelipatan' => '1',
                    'end_date' => '1',
                ],
                [
                    'name' => 'Pikachu After Gym',
                    'slug' => '1',
                    'description' => 'Pikachu After Gym',
                    'price' => '0',
                    'stock' => '0',
                    'user_id' => '1',
                    'kategori_id' => '1',
                    'sku' => '1',
                    'weight' => '1',
                    'asuransi' => '1',
                    'long' => '1',
                    'width' => '1',
                    'height' => '1',
                    'status' => '1',
                    'views' => '1',
                    'kodisi' => '1',
                    'kelipatan' => '1',
                    'end_date' => '1',
                ],
                [
                    'name' => 'Father and Son',
                    'slug' => '1',
                    'description' => 'Father and Son',
                    'price' => '0',
                    'stock' => '0',
                    'user_id' => '1',
                    'kategori_id' => '1',
                    'sku' => '1',
                    'weight' => '1',
                    'asuransi' => '1',
                    'long' => '1',
                    'width' => '1',
                    'height' => '1',
                    'status' => '1',
                    'views' => '1',
                    'kodisi' => '1',
                    'kelipatan' => '1',
                    'end_date' => '1',
                ],
                [
                    'name' => 'Anaq Sendja',
                    'slug' => '1',
                    'description' => 'Anaq Sendja',
                    'price' => '0',
                    'stock' => '0',
                    'user_id' => '1',
                    'kategori_id' => '1',
                    'sku' => '1',
                    'weight' => '1',
                    'asuransi' => '1',
                    'long' => '1',
                    'width' => '1',
                    'height' => '1',
                    'status' => '1',
                    'views' => '1',
                    'kodisi' => '1',
                    'kelipatan' => '1',
                    'end_date' => '1',
                ]
            ];
            DB::table('products')->insert($data);
    }
}
