<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         $data = [
                [
                    'title' => 'Meramu',
                    'slug' => Str::slug('Meramu'),
                    'description' => 'meramu',
                    'price' => '0',
                    'diskon' => '0',
                    'stock' => '0',
                    'user_id' => '1',
                    'kategori_id' => '1',
                    'karya_id' => '1',
                    'sku' => '1',
                    'weight' => '1',
                    'asuransi' => '1',
                    'long' => '1',
                    'width' => '1',
                    'height' => '1',
                    'status' => '1',
                    'views' => '1',
                    'kondisi' => '1',
                    'kelipatan' => '1',
                    'end_date' => now(),
                ],
                [
                    'title' => 'Love Language',
                    'slug' => Str::slug('Love Language'),
                    'description' => 'Love Language',
                    'price' => '0',
                    'diskon' => '0',
                    'stock' => '0',
                    'user_id' => '1',
                    'kategori_id' => '1',
                    'karya_id' => '1',
                    'sku' => '1',
                    'weight' => '1',
                    'asuransi' => '1',
                    'long' => '1',
                    'width' => '1',
                    'height' => '1',
                    'status' => '1',
                    'views' => '1',
                    'kondisi' => '1',
                    'kelipatan' => '1',
                    'end_date' => now(),
                ],
                [
                    'title' => 'Friend 4ever',
                    'slug' => Str::slug('Friend 4ever'),
                    'description' => 'Friend 4ever',
                    'price' => '0',
                    'diskon' => '0',
                    'stock' => '0',
                    'user_id' => '1',
                    'kategori_id' => '1',
                    'karya_id' => '1',
                    'sku' => '1',
                    'weight' => '1',
                    'asuransi' => '1',
                    'long' => '1',
                    'width' => '1',
                    'height' => '1',
                    'status' => '1',
                    'views' => '1',
                    'kondisi' => '1',
                    'kelipatan' => '1',
                    'end_date' => now(),
                ],
                [
                    'title' => 'Team',
                    'slug' => Str::slug('Team'),
                    'description' => 'Team',
                    'price' => '0',
                    'diskon' => '0',
                    'stock' => '0',
                    'user_id' => '1',
                    'kategori_id' => '1',
                    'karya_id' => '1',
                    'sku' => '1',
                    'weight' => '1',
                    'asuransi' => '1',
                    'long' => '1',
                    'width' => '1',
                    'height' => '1',
                    'status' => '1',
                    'views' => '1',
                    'kondisi' => '1',
                    'kelipatan' => '1',
                    'end_date' => now(),
                ],
                [
                    'title' => 'Boyband',
                    'slug' => Str::slug('Boyband'),
                    'description' => 'Boyband',
                    'price' => '0',
                    'diskon' => '0',
                    'stock' => '0',
                    'user_id' => '1',
                    'kategori_id' => '1',
                    'karya_id' => '1',
                    'sku' => '1',
                    'weight' => '1',
                    'asuransi' => '1',
                    'long' => '1',
                    'width' => '1',
                    'height' => '1',
                    'status' => '1',
                    'views' => '1',
                    'kondisi' => '1',
                    'kelipatan' => '1',
                    'end_date' => now(),
                ],
                [
                    'title' => 'Pikachu After Gym',
                    'slug' => Str::slug('Pikachu After Gym'),
                    'description' => 'Pikachu After Gym',
                    'price' => '0',
                    'diskon' => '0',
                    'stock' => '0',
                    'user_id' => '1',
                    'kategori_id' => '1',
                    'karya_id' => '1',
                    'sku' => '1',
                    'weight' => '1',
                    'asuransi' => '1',
                    'long' => '1',
                    'width' => '1',
                    'height' => '1',
                    'status' => '1',
                    'views' => '1',
                    'kondisi' => '1',
                    'kelipatan' => '1',
                    'end_date' => now(),
                ],
                [
                    'title' => 'Father and Son',
                    'slug' => Str::slug('Father and Son'),
                    'description' => 'Father and Son',
                    'price' => '0',
                    'diskon' => '0',
                    'stock' => '0',
                    'user_id' => '1',
                    'kategori_id' => '1',
                    'karya_id' => '1',
                    'sku' => '1',
                    'weight' => '1',
                    'asuransi' => '1',
                    'long' => '1',
                    'width' => '1',
                    'height' => '1',
                    'status' => '1',
                    'views' => '1',
                    'kondisi' => '1',
                    'kelipatan' => '1',
                    'end_date' => now(),
                ],
                [
                    'title' => 'Anaq Sendja',
                    'slug' => Str::slug('Anaq Sendja'),
                    'description' => 'Anaq Sendja',
                    'price' => '0',
                    'diskon' => '0',
                    'stock' => '0',
                    'user_id' => '1',
                    'kategori_id' => '1',
                    'karya_id' => '1',
                    'sku' => '1',
                    'weight' => '1',
                    'asuransi' => '1',
                    'long' => '1',
                    'width' => '1',
                    'height' => '1',
                    'status' => '1',
                    'views' => '1',
                    'kondisi' => '1',
                    'kelipatan' => '1',
                    'end_date' => now(),
                ]
            ];
            DB::table('products')->insert($data);
    }
}
